<?xml version="1.0" encoding="utf-8"?><Database Name="EntityFrameworkTest" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=IT-JCHERRI-LT;Initial Catalog=EntityFrameworkTest;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EntityFrameworkTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OrderProduct" Member="OrderProduct1s">
    <Type Name="OrderProduct1">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Person_OrderProduct1" Member="Person1" ThisKey="PersonID" OtherKey="PersonID" Type="Person1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Person1s">
    <Type Name="Person1">
      <Column Name="PersonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Person_OrderProduct1" Member="OrderProduct1s" ThisKey="PersonID" OtherKey="PersonID" Type="OrderProduct1" />
    </Type>
  </Table>
</Database>